name: API Test Automation

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  api-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Newman
        run: npm install -g newman newman-reporter-html

      - name: Run API Tests
        run: |
          newman run Oyinuah-DelveApiTask9.postman_collection.json -r cli,html --reporter-html-export results.html

      - name: Upload Test Report
        uses: actions/upload-artifact@v3
        with:
          name: test-report
          path: results.html
